package currency_provider

import (
	"encoding/json"
	"gopkg.in/mgo.v2/bson"
	"time"
)

type Quotes struct {
	AED json.Number `json:"USDAED,omitempty" bson:"AED,omitempty"`
	AFN json.Number `json:"USDAFN,omitempty" bson:"AFN,omitempty"`
	ALL json.Number `json:"USDALL,omitempty" bson:"ALL,omitempty"`
	AMD json.Number `json:"USDAMD,omitempty" bson:"AMD,omitempty"`
	ANG json.Number `json:"USDANG,omitempty" bson:"ANG,omitempty"`
	AOA json.Number `json:"USDAOA,omitempty" bson:"AOA,omitempty"`
	ARS json.Number `json:"USDARS,omitempty" bson:"ARS,omitempty"`
	AUD json.Number `json:"USDAUD,omitempty" bson:"AUD,omitempty"`
	AWG json.Number `json:"USDAWG,omitempty" bson:"AWG,omitempty"`
	AZN json.Number `json:"USDAZN,omitempty" bson:"AZN,omitempty"`
	BAM json.Number `json:"USDBAM,omitempty" bson:"BAM,omitempty"`
	BBD json.Number `json:"USDBBD,omitempty" bson:"BBD,omitempty"`
	BDT json.Number `json:"USDBDT,omitempty" bson:"BDT,omitempty"`
	BGN json.Number `json:"USDBGN,omitempty" bson:"BGN,omitempty"`
	BHD json.Number `json:"USDBHD,omitempty" bson:"BHD,omitempty"`
	BIF json.Number `json:"USDBIF,omitempty" bson:"BIF,omitempty"`
	BMD json.Number `json:"USDBMD,omitempty" bson:"BMD,omitempty"`
	BND json.Number `json:"USDBND,omitempty" bson:"BND,omitempty"`
	BOB json.Number `json:"USDBOB,omitempty" bson:"BOB,omitempty"`
	BRL json.Number `json:"USDBRL,omitempty" bson:"BRL,omitempty"`
	BSD json.Number `json:"USDBSD,omitempty" bson:"BSD,omitempty"`
	BTC json.Number `json:"USDBTC,omitempty" bson:"BTC,omitempty"`
	BTN json.Number `json:"USDBTN,omitempty" bson:"BTN,omitempty"`
	BWP json.Number `json:"USDBWP,omitempty" bson:"BWP,omitempty"`
	BYN json.Number `json:"USDBYN,omitempty" bson:"BYN,omitempty"`
	BYR json.Number `json:"USDBYR,omitempty" bson:"BYR,omitempty"`
	BZD json.Number `json:"USDBZD,omitempty" bson:"BZD,omitempty"`
	CAD json.Number `json:"USDCAD,omitempty" bson:"CAD,omitempty"`
	CDF json.Number `json:"USDCDF,omitempty" bson:"CDF,omitempty"`
	CHF json.Number `json:"USDCHF,omitempty" bson:"CHF,omitempty"`
	CLF json.Number `json:"USDCLF,omitempty" bson:"CLF,omitempty"`
	CLP json.Number `json:"USDCLP,omitempty" bson:"CLP,omitempty"`
	CNY json.Number `json:"USDCNY,omitempty" bson:"CNY,omitempty"`
	COP json.Number `json:"USDCOP,omitempty" bson:"COP,omitempty"`
	CRC json.Number `json:"USDCRC,omitempty" bson:"CRC,omitempty"`
	CUC json.Number `json:"USDCUC,omitempty" bson:"CUC,omitempty"`
	CUP json.Number `json:"USDCUP,omitempty" bson:"CUP,omitempty"`
	CVE json.Number `json:"USDCVE,omitempty" bson:"CVE,omitempty"`
	CZK json.Number `json:"USDCZK,omitempty" bson:"CZK,omitempty"`
	DJF json.Number `json:"USDDJF,omitempty" bson:"DJF,omitempty"`
	DKK json.Number `json:"USDDKK,omitempty" bson:"DKK,omitempty"`
	DOP json.Number `json:"USDDOP,omitempty" bson:"DOP,omitempty"`
	DZD json.Number `json:"USDDZD,omitempty" bson:"DZD,omitempty"`
	EGP json.Number `json:"USDEGP,omitempty" bson:"EGP,omitempty"`
	ERN json.Number `json:"USDERN,omitempty" bson:"ERN,omitempty"`
	ETB json.Number `json:"USDETB,omitempty" bson:"ETB,omitempty"`
	EUR json.Number `json:"USDEUR,omitempty" bson:"EUR,omitempty"`
	FJD json.Number `json:"USDFJD,omitempty" bson:"FJD,omitempty"`
	FKP json.Number `json:"USDFKP,omitempty" bson:"FKP,omitempty"`
	GBP json.Number `json:"USDGBP,omitempty" bson:"GBP,omitempty"`
	GEL json.Number `json:"USDGEL,omitempty" bson:"GEL,omitempty"`
	GGP json.Number `json:"USDGGP,omitempty" bson:"GGP,omitempty"`
	GHS json.Number `json:"USDGHS,omitempty" bson:"GHS,omitempty"`
	GIP json.Number `json:"USDGIP,omitempty" bson:"GIP,omitempty"`
	GMD json.Number `json:"USDGMD,omitempty" bson:"GMD,omitempty"`
	GNF json.Number `json:"USDGNF,omitempty" bson:"GNF,omitempty"`
	GTQ json.Number `json:"USDGTQ,omitempty" bson:"GTQ,omitempty"`
	GYD json.Number `json:"USDGYD,omitempty" bson:"GYD,omitempty"`
	HKD json.Number `json:"USDHKD,omitempty" bson:"HKD,omitempty"`
	HNL json.Number `json:"USDHNL,omitempty" bson:"HNL,omitempty"`
	HRK json.Number `json:"USDHRK,omitempty" bson:"HRK,omitempty"`
	HTG json.Number `json:"USDHTG,omitempty" bson:"HTG,omitempty"`
	HUF json.Number `json:"USDHUF,omitempty" bson:"HUF,omitempty"`
	IDR json.Number `json:"USDIDR,omitempty" bson:"IDR,omitempty"`
	ILS json.Number `json:"USDILS,omitempty" bson:"ILS,omitempty"`
	IMP json.Number `json:"USDIMP,omitempty" bson:"IMP,omitempty"`
	INR json.Number `json:"USDINR,omitempty" bson:"INR,omitempty"`
	IQD json.Number `json:"USDIQD,omitempty" bson:"IQD,omitempty"`
	IRR json.Number `json:"USDIRR,omitempty" bson:"IRR,omitempty"`
	ISK json.Number `json:"USDISK,omitempty" bson:"ISK,omitempty"`
	JEP json.Number `json:"USDJEP,omitempty" bson:"JEP,omitempty"`
	JMD json.Number `json:"USDJMD,omitempty" bson:"JMD,omitempty"`
	JOD json.Number `json:"USDJOD,omitempty" bson:"JOD,omitempty"`
	JPY json.Number `json:"USDJPY,omitempty" bson:"JPY,omitempty"`
	KES json.Number `json:"USDKES,omitempty" bson:"KES,omitempty"`
	KGS json.Number `json:"USDKGS,omitempty" bson:"KGS,omitempty"`
	KHR json.Number `json:"USDKHR,omitempty" bson:"KHR,omitempty"`
	KMF json.Number `json:"USDKMF,omitempty" bson:"KMF,omitempty"`
	KPW json.Number `json:"USDKPW,omitempty" bson:"KPW,omitempty"`
	KRW json.Number `json:"USDKRW,omitempty" bson:"KRW,omitempty"`
	KWD json.Number `json:"USDKWD,omitempty" bson:"KWD,omitempty"`
	KYD json.Number `json:"USDKYD,omitempty" bson:"KYD,omitempty"`
	KZT json.Number `json:"USDKZT,omitempty" bson:"KZT,omitempty"`
	LAK json.Number `json:"USDLAK,omitempty" bson:"LAK,omitempty"`
	LBP json.Number `json:"USDLBP,omitempty" bson:"LBP,omitempty"`
	LKR json.Number `json:"USDLKR,omitempty" bson:"LKR,omitempty"`
	LRD json.Number `json:"USDLRD,omitempty" bson:"LRD,omitempty"`
	LSL json.Number `json:"USDLSL,omitempty" bson:"LSL,omitempty"`
	LTL json.Number `json:"USDLTL,omitempty" bson:"LTL,omitempty"`
	LVL json.Number `json:"USDLVL,omitempty" bson:"LVL,omitempty"`
	LYD json.Number `json:"USDLYD,omitempty" bson:"LYD,omitempty"`
	MAD json.Number `json:"USDMAD,omitempty" bson:"MAD,omitempty"`
	MDL json.Number `json:"USDMDL,omitempty" bson:"MDL,omitempty"`
	MGA json.Number `json:"USDMGA,omitempty" bson:"MGA,omitempty"`
	MKD json.Number `json:"USDMKD,omitempty" bson:"MKD,omitempty"`
	MMK json.Number `json:"USDMMK,omitempty" bson:"MMK,omitempty"`
	MNT json.Number `json:"USDMNT,omitempty" bson:"MNT,omitempty"`
	MOP json.Number `json:"USDMOP,omitempty" bson:"MOP,omitempty"`
	MRO json.Number `json:"USDMRO,omitempty" bson:"MRO,omitempty"`
	MUR json.Number `json:"USDMUR,omitempty" bson:"MUR,omitempty"`
	MVR json.Number `json:"USDMVR,omitempty" bson:"MVR,omitempty"`
	MWK json.Number `json:"USDMWK,omitempty" bson:"MWK,omitempty"`
	MXN json.Number `json:"USDMXN,omitempty" bson:"MXN,omitempty"`
	MYR json.Number `json:"USDMYR,omitempty" bson:"MYR,omitempty"`
	MZN json.Number `json:"USDMZN,omitempty" bson:"MZN,omitempty"`
	NAD json.Number `json:"USDNAD,omitempty" bson:"NAD,omitempty"`
	NGN json.Number `json:"USDNGN,omitempty" bson:"NGN,omitempty"`
	NIO json.Number `json:"USDNIO,omitempty" bson:"NIO,omitempty"`
	NOK json.Number `json:"USDNOK,omitempty" bson:"NOK,omitempty"`
	NPR json.Number `json:"USDNPR,omitempty" bson:"NPR,omitempty"`
	NZD json.Number `json:"USDNZD,omitempty" bson:"NZD,omitempty"`
	OMR json.Number `json:"USDOMR,omitempty" bson:"OMR,omitempty"`
	PAB json.Number `json:"USDPAB,omitempty" bson:"PAB,omitempty"`
	PEN json.Number `json:"USDPEN,omitempty" bson:"PEN,omitempty"`
	PGK json.Number `json:"USDPGK,omitempty" bson:"PGK,omitempty"`
	PHP json.Number `json:"USDPHP,omitempty" bson:"PHP,omitempty"`
	PKR json.Number `json:"USDPKR,omitempty" bson:"PKR,omitempty"`
	PLN json.Number `json:"USDPLN,omitempty" bson:"PLN,omitempty"`
	PYG json.Number `json:"USDPYG,omitempty" bson:"PYG,omitempty"`
	QAR json.Number `json:"USDQAR,omitempty" bson:"QAR,omitempty"`
	RON json.Number `json:"USDRON,omitempty" bson:"RON,omitempty"`
	RSD json.Number `json:"USDRSD,omitempty" bson:"RSD,omitempty"`
	RUB json.Number `json:"USDRUB,omitempty" bson:"RUB,omitempty"`
	RWF json.Number `json:"USDRWF,omitempty" bson:"RWF,omitempty"`
	SAR json.Number `json:"USDSAR,omitempty" bson:"SAR,omitempty"`
	SBD json.Number `json:"USDSBD,omitempty" bson:"SBD,omitempty"`
	SCR json.Number `json:"USDSCR,omitempty" bson:"SCR,omitempty"`
	SDG json.Number `json:"USDSDG,omitempty" bson:"SDG,omitempty"`
	SEK json.Number `json:"USDSEK,omitempty" bson:"SEK,omitempty"`
	SGD json.Number `json:"USDSGD,omitempty" bson:"SGD,omitempty"`
	SHP json.Number `json:"USDSHP,omitempty" bson:"SHP,omitempty"`
	SLL json.Number `json:"USDSLL,omitempty" bson:"SLL,omitempty"`
	SOS json.Number `json:"USDSOS,omitempty" bson:"SOS,omitempty"`
	SRD json.Number `json:"USDSRD,omitempty" bson:"SRD,omitempty"`
	STD json.Number `json:"USDSTD,omitempty" bson:"STD,omitempty"`
	SVC json.Number `json:"USDSVC,omitempty" bson:"SVC,omitempty"`
	SYP json.Number `json:"USDSYP,omitempty" bson:"SYP,omitempty"`
	SZL json.Number `json:"USDSZL,omitempty" bson:"SZL,omitempty"`
	THB json.Number `json:"USDTHB,omitempty" bson:"THB,omitempty"`
	TJS json.Number `json:"USDTJS,omitempty" bson:"TJS,omitempty"`
	TMT json.Number `json:"USDTMT,omitempty" bson:"TMT,omitempty"`
	TND json.Number `json:"USDTND,omitempty" bson:"TND,omitempty"`
	TOP json.Number `json:"USDTOP,omitempty" bson:"TOP,omitempty"`
	TRY json.Number `json:"USDTRY,omitempty" bson:"TRY,omitempty"`
	TTD json.Number `json:"USDTTD,omitempty" bson:"TTD,omitempty"`
	TWD json.Number `json:"USDTWD,omitempty" bson:"TWD,omitempty"`
	TZS json.Number `json:"USDTZS,omitempty" bson:"TZS,omitempty"`
	UAH json.Number `json:"USDUAH,omitempty" bson:"UAH,omitempty"`
	UGX json.Number `json:"USDUGX,omitempty" bson:"UGX,omitempty"`
	USD json.Number `json:"USDUSD,omitempty" bson:"USD,omitempty"`
	UYU json.Number `json:"USDUYU,omitempty" bson:"UYU,omitempty"`
	UZS json.Number `json:"USDUZS,omitempty" bson:"UZS,omitempty"`
	VEF json.Number `json:"USDVEF,omitempty" bson:"VEF,omitempty"`
	VND json.Number `json:"USDVND,omitempty" bson:"VND,omitempty"`
	VUV json.Number `json:"USDVUV,omitempty" bson:"VUV,omitempty"`
	WST json.Number `json:"USDWST,omitempty" bson:"WST,omitempty"`
	XAF json.Number `json:"USDXAF,omitempty" bson:"XAF,omitempty"`
	XAG json.Number `json:"USDXAG,omitempty" bson:"XAG,omitempty"`
	XAU json.Number `json:"USDXAU,omitempty" bson:"XAU,omitempty"`
	XCD json.Number `json:"USDXCD,omitempty" bson:"SCD,omitempty"`
	XDR json.Number `json:"USDXDR,omitempty" bson:"XDR,omitempty"`
	XOF json.Number `json:"USDXOF,omitempty" bson:"XOF,omitempty"`
	XPF json.Number `json:"USDXPF,omitempty" bson:"XPF,omitempty"`
	YER json.Number `json:"USDYER,omitempty" bson:"YER,omitempty"`
	ZAR json.Number `json:"USDZAR,omitempty" bson:"ZAR,omitempty"`
	ZMK json.Number `json:"USDZMK,omitempty" bson:"ZMK,omitempty"`
	ZMW json.Number `json:"USDZMW,omitempty" bson:"ZMW,omitempty"`
	ZWL json.Number `json:"USDZWL,omitempty" bson:"ZWL,omitempty"`
}

type Currency struct {
	ID bson.ObjectId `bson:"_id"`
	Quotes Quotes `json:"quotes"`
	Source string `json:"source" bson:"name"`
	DateCreation time.Time `bson:"name"`
}