package currency_provider

import "encoding/json"

type Quotes struct {
	USDAED json.Number `json:"USDAED,omitempty"`
	USDAFN json.Number `json:"USDAFN,omitempty"`
	USDALL json.Number `json:"USDALL,omitempty"`
	USDAMD json.Number `json:"USDAMD,omitempty"`
	USDANG json.Number `json:"USDANG,omitempty"`
	USDAOA json.Number `json:"USDAOA,omitempty"`
	USDARS json.Number `json:"USDARS,omitempty"`
	USDAUD json.Number `json:"USDAUD,omitempty"`
	USDAWG json.Number `json:"USDAWG,omitempty"`
	USDAZN json.Number `json:"USDAZN,omitempty"`
	USDBAM json.Number `json:"USDBAM,omitempty"`
	USDBBD json.Number `json:"USDBBD,omitempty"`
	USDBDT json.Number `json:"USDBDT,omitempty"`
	USDBGN json.Number `json:"USDBGN,omitempty"`
	USDBHD json.Number `json:"USDBHD,omitempty"`
	USDBIF json.Number `json:"USDBIF,omitempty"`
	USDBMD json.Number `json:"USDBMD,omitempty"`
	USDBND json.Number `json:"USDBND,omitempty"`
	USDBOB json.Number `json:"USDBOB,omitempty"`
	USDBRL json.Number `json:"USDBRL,omitempty"`
	USDBSD json.Number `json:"USDBSD,omitempty"`
	USDBTC json.Number `json:"USDBTC,omitempty"`
	USDBTN json.Number `json:"USDBTN,omitempty"`
	USDBWP json.Number `json:"USDBWP,omitempty"`
	USDBYN json.Number `json:"USDBYN,omitempty"`
	USDBYR json.Number `json:"USDBYR,omitempty"`
	USDBZD json.Number `json:"USDBZD,omitempty"`
	USDCAD json.Number `json:"USDCAD,omitempty"`
	USDCDF json.Number `json:"USDCDF,omitempty"`
	USDCHF json.Number `json:"USDCHF,omitempty"`
	USDCLF json.Number `json:"USDCLF,omitempty"`
	USDCLP json.Number `json:"USDCLP,omitempty"`
	USDCNY json.Number `json:"USDCNY,omitempty"`
	USDCOP json.Number `json:"USDCOP,omitempty"`
	USDCRC json.Number `json:"USDCRC,omitempty"`
	USDCUC json.Number `json:"USDCUC,omitempty"`
	USDCUP json.Number `json:"USDCUP,omitempty"`
	USDCVE json.Number `json:"USDCVE,omitempty"`
	USDCZK json.Number `json:"USDCZK,omitempty"`
	USDDJF json.Number `json:"USDDJF,omitempty"`
	USDDKK json.Number `json:"USDDKK,omitempty"`
	USDDOP json.Number `json:"USDDOP,omitempty"`
	USDDZD json.Number `json:"USDDZD,omitempty"`
	USDEGP json.Number `json:"USDEGP,omitempty"`
	USDERN json.Number `json:"USDERN,omitempty"`
	USDETB json.Number `json:"USDETB,omitempty"`
	USDEUR json.Number `json:"USDEUR,omitempty"`
	USDFJD json.Number `json:"USDFJD,omitempty"`
	USDFKP json.Number `json:"USDFKP,omitempty"`
	USDGBP json.Number `json:"USDGBP,omitempty"`
	USDGEL json.Number `json:"USDGEL,omitempty"`
	USDGGP json.Number `json:"USDGGP,omitempty"`
	USDGHS json.Number `json:"USDGHS,omitempty"`
	USDGIP json.Number `json:"USDGIP,omitempty"`
	USDGMD json.Number `json:"USDGMD,omitempty"`
	USDGNF json.Number `json:"USDGNF,omitempty"`
	USDGTQ json.Number `json:"USDGTQ,omitempty"`
	USDGYD json.Number `json:"USDGYD,omitempty"`
	USDHKD json.Number `json:"USDHKD,omitempty"`
	USDHNL json.Number `json:"USDHNL,omitempty"`
	USDHRK json.Number `json:"USDHRK,omitempty"`
	USDHTG json.Number `json:"USDHTG,omitempty"`
	USDHUF json.Number `json:"USDHUF,omitempty"`
	USDIDR json.Number `json:"USDIDR,omitempty"`
	USDILS json.Number `json:"USDILS,omitempty"`
	USDIMP json.Number `json:"USDIMP,omitempty"`
	USDINR json.Number `json:"USDINR,omitempty"`
	USDIQD json.Number `json:"USDIQD,omitempty"`
	USDIRR json.Number `json:"USDIRR,omitempty"`
	USDISK json.Number `json:"USDISK,omitempty"`
	USDJEP json.Number `json:"USDJEP,omitempty"`
	USDJMD json.Number `json:"USDJMD,omitempty"`
	USDJOD json.Number `json:"USDJOD,omitempty"`
	USDJPY json.Number `json:"USDJPY,omitempty"`
	USDKES json.Number `json:"USDKES,omitempty"`
	USDKGS json.Number `json:"USDKGS,omitempty"`
	USDKHR json.Number `json:"USDKHR,omitempty"`
	USDKMF json.Number `json:"USDKMF,omitempty"`
	USDKPW json.Number `json:"USDKPW,omitempty"`
	USDKRW json.Number `json:"USDKRW,omitempty"`
	USDKWD json.Number `json:"USDKWD,omitempty"`
	USDKYD json.Number `json:"USDKYD,omitempty"`
	USDKZT json.Number `json:"USDKZT,omitempty"`
	USDLAK json.Number `json:"USDLAK,omitempty"`
	USDLBP json.Number `json:"USDLBP,omitempty"`
	USDLKR json.Number `json:"USDLKR,omitempty"`
	USDLRD json.Number `json:"USDLRD,omitempty"`
	USDLSL json.Number `json:"USDLSL,omitempty"`
	USDLTL json.Number `json:"USDLTL,omitempty"`
	USDLVL json.Number `json:"USDLVL,omitempty"`
	USDLYD json.Number `json:"USDLYD,omitempty"`
	USDMAD json.Number `json:"USDMAD,omitempty"`
	USDMDL json.Number `json:"USDMDL,omitempty"`
	USDMGA json.Number `json:"USDMGA,omitempty"`
	USDMKD json.Number `json:"USDMKD,omitempty"`
	USDMMK json.Number `json:"USDMMK,omitempty"`
	USDMNT json.Number `json:"USDMNT,omitempty"`
	USDMOP json.Number `json:"USDMOP,omitempty"`
	USDMRO json.Number `json:"USDMRO,omitempty"`
	USDMUR json.Number `json:"USDMUR,omitempty"`
	USDMVR json.Number `json:"USDMVR,omitempty"`
	USDMWK json.Number `json:"USDMWK,omitempty"`
	USDMXN json.Number `json:"USDMXN,omitempty"`
	USDMYR json.Number `json:"USDMYR,omitempty"`
	USDMZN json.Number `json:"USDMZN,omitempty"`
	USDNAD json.Number `json:"USDNAD,omitempty"`
	USDNGN json.Number `json:"USDNGN,omitempty"`
	USDNIO json.Number `json:"USDNIO,omitempty"`
	USDNOK json.Number `json:"USDNOK,omitempty"`
	USDNPR json.Number `json:"USDNPR,omitempty"`
	USDNZD json.Number `json:"USDNZD,omitempty"`
	USDOMR json.Number `json:"USDOMR,omitempty"`
	USDPAB json.Number `json:"USDPAB,omitempty"`
	USDPEN json.Number `json:"USDPEN,omitempty"`
	USDPGK json.Number `json:"USDPGK,omitempty"`
	USDPHP json.Number `json:"USDPHP,omitempty"`
	USDPKR json.Number `json:"USDPKR,omitempty"`
	USDPLN json.Number `json:"USDPLN,omitempty"`
	USDPYG json.Number `json:"USDPYG,omitempty"`
	USDQAR json.Number `json:"USDQAR,omitempty"`
	USDRON json.Number `json:"USDRON,omitempty"`
	USDRSD json.Number `json:"USDRSD,omitempty"`
	USDRUB json.Number `json:"USDRUB,omitempty"`
	USDRWF json.Number `json:"USDRWF,omitempty"`
	USDSAR json.Number `json:"USDSAR,omitempty"`
	USDSBD json.Number `json:"USDSBD,omitempty"`
	USDSCR json.Number `json:"USDSCR,omitempty"`
	USDSDG json.Number `json:"USDSDG,omitempty"`
	USDSEK json.Number `json:"USDSEK,omitempty"`
	USDSGD json.Number `json:"USDSGD,omitempty"`
	USDSHP json.Number `json:"USDSHP,omitempty"`
	USDSLL json.Number `json:"USDSLL,omitempty"`
	USDSOS json.Number `json:"USDSOS,omitempty"`
	USDSRD json.Number `json:"USDSRD,omitempty"`
	USDSTD json.Number `json:"USDSTD,omitempty"`
	USDSVC json.Number `json:"USDSVC,omitempty"`
	USDSYP json.Number `json:"USDSYP,omitempty"`
	USDSZL json.Number `json:"USDSZL,omitempty"`
	USDTHB json.Number `json:"USDTHB,omitempty"`
	USDTJS json.Number `json:"USDTJS,omitempty"`
	USDTMT json.Number `json:"USDTMT,omitempty"`
	USDTND json.Number `json:"USDTND,omitempty"`
	USDTOP json.Number `json:"USDTOP,omitempty"`
	USDTRY json.Number `json:"USDTRY,omitempty"`
	USDTTD json.Number `json:"USDTTD,omitempty"`
	USDTWD json.Number `json:"USDTWD,omitempty"`
	USDTZS json.Number `json:"USDTZS,omitempty"`
	USDUAH json.Number `json:"USDUAH,omitempty"`
	USDUGX json.Number `json:"USDUGX,omitempty"`
	USDUSD json.Number `json:"USDUSD,omitempty"`
	USDUYU json.Number `json:"USDUYU,omitempty"`
	USDUZS json.Number `json:"USDUZS,omitempty"`
	USDVEF json.Number `json:"USDVEF,omitempty"`
	USDVND json.Number `json:"USDVND,omitempty"`
	USDVUV json.Number `json:"USDVUV,omitempty"`
	USDWST json.Number `json:"USDWST,omitempty"`
	USDXAF json.Number `json:"USDXAF,omitempty"`
	USDXAG json.Number `json:"USDXAG,omitempty"`
	USDXAU json.Number `json:"USDXAU,omitempty"`
	USDXCD json.Number `json:"USDXCD,omitempty"`
	USDXDR json.Number `json:"USDXDR,omitempty"`
	USDXOF json.Number `json:"USDXOF,omitempty"`
	USDXPF json.Number `json:"USDXPF,omitempty"`
	USDYER json.Number `json:"USDYER,omitempty"`
	USDZAR json.Number `json:"USDZAR,omitempty"`
	USDZMK json.Number `json:"USDZMK,omitempty"`
	USDZMW json.Number `json:"USDZMW,omitempty"`
	USDZWL json.Number `json:"USDZWL,omitempty"`
}

type Currency struct {
	Quotes Quotes `json:"quotes"`
	Source string `json:"source"`
}