package currency_provider

import "encoding/json"

type Quotes struct {
	USDAED json.Number `json:"USDAED"`
	USDAFN json.Number `json:"USDAFN"`
	USDALL json.Number `json:"USDALL"`
	USDAMD json.Number `json:"USDAMD"`
	USDANG json.Number `json:"USDANG"`
	USDAOA json.Number `json:"USDAOA"`
	USDARS json.Number `json:"USDARS"`
	USDAUD json.Number `json:"USDAUD"`
	USDAWG json.Number `json:"USDAWG"`
	USDAZN json.Number `json:"USDAZN"`
	USDBAM json.Number `json:"USDBAM"`
	USDBBD json.Number `json:"USDBBD"`
	USDBDT json.Number `json:"USDBDT"`
	USDBGN json.Number `json:"USDBGN"`
	USDBHD json.Number `json:"USDBHD"`
	USDBIF json.Number `json:"USDBIF"`
	USDBMD json.Number `json:"USDBMD"`
	USDBND json.Number `json:"USDBND"`
	USDBOB json.Number `json:"USDBOB"`
	USDBRL json.Number `json:"USDBRL"`
	USDBSD json.Number `json:"USDBSD"`
	USDBTC json.Number `json:"USDBTC"`
	USDBTN json.Number `json:"USDBTN"`
	USDBWP json.Number `json:"USDBWP"`
	USDBYN json.Number `json:"USDBYN"`
	USDBYR json.Number `json:"USDBYR"`
	USDBZD json.Number `json:"USDBZD"`
	USDCAD json.Number `json:"USDCAD"`
	USDCDF json.Number `json:"USDCDF"`
	USDCHF json.Number `json:"USDCHF"`
	USDCLF json.Number `json:"USDCLF"`
	USDCLP json.Number `json:"USDCLP"`
	USDCNY json.Number `json:"USDCNY"`
	USDCOP json.Number `json:"USDCOP"`
	USDCRC json.Number `json:"USDCRC"`
	USDCUC json.Number `json:"USDCUC"`
	USDCUP json.Number `json:"USDCUP"`
	USDCVE json.Number `json:"USDCVE"`
	USDCZK json.Number `json:"USDCZK"`
	USDDJF json.Number `json:"USDDJF"`
	USDDKK json.Number `json:"USDDKK"`
	USDDOP json.Number `json:"USDDOP"`
	USDDZD json.Number `json:"USDDZD"`
	USDEGP json.Number `json:"USDEGP"`
	USDERN json.Number `json:"USDERN"`
	USDETB json.Number `json:"USDETB"`
	USDEUR json.Number `json:"USDEUR"`
	USDFJD json.Number `json:"USDFJD"`
	USDFKP json.Number `json:"USDFKP"`
	USDGBP json.Number `json:"USDGBP"`
	USDGEL json.Number `json:"USDGEL"`
	USDGGP json.Number `json:"USDGGP"`
	USDGHS json.Number `json:"USDGHS"`
	USDGIP json.Number `json:"USDGIP"`
	USDGMD json.Number `json:"USDGMD"`
	USDGNF json.Number `json:"USDGNF"`
	USDGTQ json.Number `json:"USDGTQ"`
	USDGYD json.Number `json:"USDGYD"`
	USDHKD json.Number `json:"USDHKD"`
	USDHNL json.Number `json:"USDHNL"`
	USDHRK json.Number `json:"USDHRK"`
	USDHTG json.Number `json:"USDHTG"`
	USDHUF json.Number `json:"USDHUF"`
	USDIDR json.Number `json:"USDIDR"`
	USDILS json.Number `json:"USDILS"`
	USDIMP json.Number `json:"USDIMP"`
	USDINR json.Number `json:"USDINR"`
	USDIQD json.Number `json:"USDIQD"`
	USDIRR json.Number `json:"USDIRR"`
	USDISK json.Number `json:"USDISK"`
	USDJEP json.Number `json:"USDJEP"`
	USDJMD json.Number `json:"USDJMD"`
	USDJOD json.Number `json:"USDJOD"`
	USDJPY json.Number `json:"USDJPY"`
	USDKES json.Number `json:"USDKES"`
	USDKGS json.Number `json:"USDKGS"`
	USDKHR json.Number `json:"USDKHR"`
	USDKMF json.Number `json:"USDKMF"`
	USDKPW json.Number `json:"USDKPW"`
	USDKRW json.Number `json:"USDKRW"`
	USDKWD json.Number `json:"USDKWD"`
	USDKYD json.Number `json:"USDKYD"`
	USDKZT json.Number `json:"USDKZT"`
	USDLAK json.Number `json:"USDLAK"`
	USDLBP json.Number `json:"USDLBP"`
	USDLKR json.Number `json:"USDLKR"`
	USDLRD json.Number `json:"USDLRD"`
	USDLSL json.Number `json:"USDLSL"`
	USDLTL json.Number `json:"USDLTL"`
	USDLVL json.Number `json:"USDLVL"`
	USDLYD json.Number `json:"USDLYD"`
	USDMAD json.Number `json:"USDMAD"`
	USDMDL json.Number `json:"USDMDL"`
	USDMGA json.Number `json:"USDMGA"`
	USDMKD json.Number `json:"USDMKD"`
	USDMMK json.Number `json:"USDMMK"`
	USDMNT json.Number `json:"USDMNT"`
	USDMOP json.Number `json:"USDMOP"`
	USDMRO json.Number `json:"USDMRO"`
	USDMUR json.Number `json:"USDMUR"`
	USDMVR json.Number `json:"USDMVR"`
	USDMWK json.Number `json:"USDMWK"`
	USDMXN json.Number `json:"USDMXN"`
	USDMYR json.Number `json:"USDMYR"`
	USDMZN json.Number `json:"USDMZN"`
	USDNAD json.Number `json:"USDNAD"`
	USDNGN json.Number `json:"USDNGN"`
	USDNIO json.Number `json:"USDNIO"`
	USDNOK json.Number `json:"USDNOK"`
	USDNPR json.Number `json:"USDNPR"`
	USDNZD json.Number `json:"USDNZD"`
	USDOMR json.Number `json:"USDOMR"`
	USDPAB json.Number `json:"USDPAB"`
	USDPEN json.Number `json:"USDPEN"`
	USDPGK json.Number `json:"USDPGK"`
	USDPHP json.Number `json:"USDPHP"`
	USDPKR json.Number `json:"USDPKR"`
	USDPLN json.Number `json:"USDPLN"`
	USDPYG json.Number `json:"USDPYG"`
	USDQAR json.Number `json:"USDQAR"`
	USDRON json.Number `json:"USDRON"`
	USDRSD json.Number `json:"USDRSD"`
	USDRUB json.Number `json:"USDRUB"`
	USDRWF json.Number `json:"USDRWF"`
	USDSAR json.Number `json:"USDSAR"`
	USDSBD json.Number `json:"USDSBD"`
	USDSCR json.Number `json:"USDSCR"`
	USDSDG json.Number `json:"USDSDG"`
	USDSEK json.Number `json:"USDSEK"`
	USDSGD json.Number `json:"USDSGD"`
	USDSHP json.Number `json:"USDSHP"`
	USDSLL json.Number `json:"USDSLL"`
	USDSOS json.Number `json:"USDSOS"`
	USDSRD json.Number `json:"USDSRD"`
	USDSTD json.Number `json:"USDSTD"`
	USDSVC json.Number `json:"USDSVC"`
	USDSYP json.Number `json:"USDSYP"`
	USDSZL json.Number `json:"USDSZL"`
	USDTHB json.Number `json:"USDTHB"`
	USDTJS json.Number `json:"USDTJS"`
	USDTMT json.Number `json:"USDTMT"`
	USDTND json.Number `json:"USDTND"`
	USDTOP json.Number `json:"USDTOP"`
	USDTRY json.Number `json:"USDTRY"`
	USDTTD json.Number `json:"USDTTD"`
	USDTWD json.Number `json:"USDTWD"`
	USDTZS json.Number `json:"USDTZS"`
	USDUAH json.Number `json:"USDUAH"`
	USDUGX json.Number `json:"USDUGX"`
	USDUSD json.Number `json:"USDUSD"`
	USDUYU json.Number `json:"USDUYU"`
	USDUZS json.Number `json:"USDUZS"`
	USDVEF json.Number `json:"USDVEF"`
	USDVND json.Number `json:"USDVND"`
	USDVUV json.Number `json:"USDVUV"`
	USDWST json.Number `json:"USDWST"`
	USDXAF json.Number `json:"USDXAF"`
	USDXAG json.Number `json:"USDXAG"`
	USDXAU json.Number `json:"USDXAU"`
	USDXCD json.Number `json:"USDXCD"`
	USDXDR json.Number `json:"USDXDR"`
	USDXOF json.Number `json:"USDXOF"`
	USDXPF json.Number `json:"USDXPF"`
	USDYER json.Number `json:"USDYER"`
	USDZAR json.Number `json:"USDZAR"`
	USDZMK json.Number `json:"USDZMK"`
	USDZMW json.Number `json:"USDZMW"`
	USDZWL json.Number `json:"USDZWL"`
}

type Currency struct {
	Quotes Quotes `json:"quotes"`
	Source string `json:"source"`
}